### ISSUE TITLE
COCO dataset 

### ISSUE THREAD

**Issue by hyunas1996** [chenfengxu714/SqueezeSegV3#14]
Thanks for the nice repository!

Is this available to do transfer learning with coco dataset?

**Comment by chenfengxu714** [comment]
You can try to directly apply the model on the coco dataset or any 2D image tasks, but I am not sure wether it works if you would transfer between semantickitti and coco dataset, because the domains are quite different. However it is still very interesting to transfer between 2D and 3D domain.
