### ISSUE TITLE
Questions concerning normalization

### ISSUE THREAD

**Issue by Solacex** [chenfengxu714/SqueezeSegV3#21]
Hello,

Thanks for your interesting work. Now we are working on run squeezeSeg on nuScenes dataset and try to obtain the mean/std for normalization. Have you tried this. If yes, would you mind share it with us?

If not, I want to know how to calculate the mean/std of each channel. calculate on the raw data or the projected data?

Best.
guangrui

**Comment by chenfengxu714** [comment]
Thanks for your appreciation.

Sorry, we don't calculate the mean/std for nuScenes dataset. The way we calculate is on projected data. But the mean/std are only slightly different with unprojected data.  Another thing is that the result would also be slightly different even your mean/std is different. So I think you can choose any one of the two methods.

**Comment by Solacex** [comment]
Hello.

Thanks for your quick response. It really helps.
