### ISSUE TITLE
Model accuracy and inference 

### ISSUE THREAD

**Issue by abhigoku10** [chenfengxu714/SqueezeSegV3#4]
@chenfengxu714  thanks for open sourcing your code , its a great work . I have few queries 
Q1. What is the impact on accuracy and fps  when the density of point cloud is around 10^3 or 10^4
Q2. In the post processing section can we obtain bounding box for the segmented objects 
Q3. can we extended squeezeseqv3 to perform instance and panoptic segmenation task 

Thanks in advance

**Comment by chenfengxu714** [comment]
Hi, thanks for your comment. 
Q1. I haven't conducted experiments on 10^3 and 10^4 points which are less than 10^5 point in the SemanticKITTI dataset. It is meaningful to do this especially in some point cloud detection dataset.
Q2. Sure, it is easy to obtain object bounding boxes based on the segmentation prediction when objects are separated. However, it would be very tricky if the same class objects gather together, e.g., cars as shown in Readme demo. An effective point cloud clustering method will help a lot.
Q3. Sure. Similar to Q2, I think a key to extend to perform above two tasks is to design an effective clustering method to separate adjacent objects with same class. We will appreciate it if others can give us more suggestions.
